### ISSUE TITLE
Could not find method compile() for arguments [com.android.support:recyclerview-v7:25.3.1]

### ISSUE THREAD

**Issue by palashmandokhot** [dandar3/android-support-v7-recyclerview#2]
In my android studio build gradle is failed i dont know how so then i check the log and i saw this error Error:Could not find method compile() for arguments [com.android.support:recyclerview-v7:25.3.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

Please install the Android Support Repository from the Android SDK Manager. Open Android SDK Manager

then i check it but android support respository is already installed version 47.0.0 i restart android studio but it shows same error how i solve this error from android studio please help me to solve this problem?

**Comment by dandar3** [comment]
Sorry, for future reference, I'm only supporting here problems with the Android libraries I'm maintaining for Eclipse.

But since you created this ticket already, at a simple search for the text you've entered in the title I found this issue on StackOverflow from 2017 which migh help you.
https://stackoverflow.com/questions/43317293/gradle-sync-failed-could-not-find-method-compile-for-arguments-com-android-s

You don't need to do all the steps you just mentioned - Android Support Repository in Android SDK Manager and so on. Those were for use with Eclipse a good few years ago, not with Android Studio. 

Android Studio and Gradle plugin they use Maven repositories to pull Maven artifacts in `%USERPROFILE%\.gradle`.

Also, that is a very old version of Android Support Library, latest one is 28.0.0 and in the meantime it all move to Android JetPack (AndroidX). https://developer.android.com/jetpack/androidx/migrate

I would suggest to update your Android Studio that will suggest you to update your Gradle Android plugin and even suggest you to move to using AndroidX dependencies instead. 

Hopefully that will solve your issue, good luck!
